/**
 * Discover directory taxonomy.
 *
 * This is the *listing* taxonomy — long, granular, and cheap to extend (the
 * backing column is unconstrained text). It is NOT the same list as the
 * collection profiles in lib/collectionProfiles, which are hand-authored UI
 * treatments. Many categories share one profile; see CATEGORY_TO_PROFILE.
 *
 * Keep alphabetical.
 */
export const COLLECTION_CATEGORIES = [
  'Advertising & Signage',
  'Antiques & Collectibles',
  'Archaeology',
  'Archives & Documents',
  'Art & Paintings',
  'Autographs & Memorabilia',
  'Automobilia & Vehicles',
  'Aviation & Maritime',
  'Banknotes & Paper Money',
  'Board Games & Puzzles',
  'Books & Manuscripts',
  'Bottles & Breweriana',
  'Cameras & Optical Equipment',
  'Ceramics & Pottery',
  'Clocks & Watches',
  'Coins & Medals',
  'Comics & Graphic Novels',
  'Decorative Arts',
  'Dolls & Bears',
  'Fashion & Clothing',
  'Film & Entertainment',
  'Fossils & Minerals',
  'Furniture',
  'Glassware & Crystal',
  'Handbags & Accessories',
  'Industrial Heritage',
  'Jewellery',
  'Kitchenalia & Domestic',
  'LEGO & Building Sets',
  'Lighting & Lamps',
  'Maps & Prints',
  'Medical & Pharmacy',
  'Militaria & Arms',
  'Model Railways',
  'Motorcycles',
  'Musical Instruments',
  'Natural History',
  'Pens & Writing Instruments',
  'Perfume & Vanity',
  'Photography',
  'Pins, Badges & Buttons',
  'Postcards',
  'Records & Music',
  'Religious & Devotional',
  'Rugs & Carpets',
  'Scientific Instruments',
  'Silver & Metalwork',
  'Sneakers & Streetwear',
  'Social History',
  'Space & Astronomy',
  'Sports & Games',
  'Sports Memorabilia',
  'Stamps & Ephemera',
  'Taxidermy',
  'Textiles',
  'Tools & Workshop',
  'Toys & Models',
  'Trading Cards & TCGs',
  'Tribal & Ethnographic',
  'Video Games & Consoles',
  'Vintage Electronics & Tech',
  'Wine & Spirits',
] as const

export type CollectionCategory = typeof COLLECTION_CATEGORIES[number]
