export const COLLECTION_CATEGORIES = [
  'Antiques & Collectibles',
  'Archaeology',
  'Archives & Documents',
  'Art & Paintings',
  'Automobilia & Vehicles',
  'Books & Manuscripts',
  'Ceramics & Pottery',
  'Clocks & Watches',
  'Coins & Medals',
  'Comics & Graphic Novels',
  'Decorative Arts',
  'Fashion & Clothing',
  'Fashion and Textiles',
  'Film & Entertainment',
  'Furniture',
  'Glassware & Crystal',
  'Industrial Heritage',
  'Jewellery',
  'Maps & Prints',
  'Militaria & Arms',
  'Musical Instruments',
  'Natural History',
  'Photography',
  'Records & Music',
  'Scientific Instruments',
  'Silver & Metalwork',
  'Social History',
  'Sports & Games',
  'Stamps & Ephemera',
  'Textiles & Rugs',
  'Toys & Models',
  'Trading Cards & TCGs',
  'Tribal & Ethnographic',
  'Video Games & Consoles',
  'Vintage Electronics & Tech',
  'Wine & Spirits',
] as const

export type CollectionCategory = typeof COLLECTION_CATEGORIES[number]
