export interface Template {
  id: string
  name: string
  description: string
  primary_color: string
  accent_color: string
  headingFont: string
  bodyFont: string
  previewBg: string
  previewText: string
  previewAccent: string
  card_radius: number
  hero_height: string
  grid_columns: number
  image_ratio: string
  card_padding: string
  card_metadata: string
  layout_variant: 'standard' | 'cover' | 'text-forward' | 'magazine' | 'sidebar' | 'minimal' | 'dramatic' | 'archival'
  supports_header_image: boolean
}

export const TEMPLATES: Template[] = [
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean, white, lots of breathing room. Lets the art speak.',
    primary_color: '#111111',
    accent_color: '#111111',
    headingFont: 'font-serif italic',
    bodyFont: 'font-sans',
    previewBg: '#ffffff',
    previewText: '#111111',
    previewAccent: '#111111',
    card_radius: 8,
    hero_height: 'compact',
    grid_columns: 4,
    image_ratio: 'square',
    card_padding: 'normal',
    card_metadata: 'title+artist',
    layout_variant: 'minimal',
    supports_header_image: false,
  },
  {
    id: 'dramatic',
    name: 'Dramatic',
    description: 'Dark and atmospheric with warm gold highlights.',
    primary_color: '#0f0e0c',
    accent_color: '#c8961e',
    headingFont: 'font-serif italic',
    bodyFont: 'font-sans',
    previewBg: '#0f0e0c',
    previewText: '#f5f2ec',
    previewAccent: '#c8961e',
    card_radius: 4,
    hero_height: 'tall',
    grid_columns: 3,
    image_ratio: 'portrait',
    card_padding: 'normal',
    card_metadata: 'full',
    layout_variant: 'dramatic',
    supports_header_image: true,
  },
  {
    id: 'archival',
    name: 'Archival',
    description: 'Warm parchment tones. Classic British museum energy.',
    primary_color: '#5c4a2a',
    accent_color: '#8b6914',
    headingFont: 'font-serif italic',
    bodyFont: 'font-sans',
    previewBg: '#f5f0e8',
    previewText: '#3a2e1e',
    previewAccent: '#8b6914',
    card_radius: 4,
    hero_height: 'medium',
    grid_columns: 4,
    image_ratio: 'square',
    card_padding: 'generous',
    card_metadata: 'full',
    layout_variant: 'archival',
    supports_header_image: false,
  },
  {
    id: 'editorial',
    name: 'Editorial',
    description: 'Bold and high-contrast. Magazine-like energy.',
    primary_color: '#cc0000',
    accent_color: '#cc0000',
    headingFont: 'font-serif',
    bodyFont: 'font-sans',
    previewBg: '#ffffff',
    previewText: '#000000',
    previewAccent: '#cc0000',
    card_radius: 0,
    hero_height: 'fullscreen',
    grid_columns: 2,
    image_ratio: 'landscape',
    card_padding: 'tight',
    card_metadata: 'title+artist',
    layout_variant: 'standard',
    supports_header_image: true,
  },
  {
    id: 'classic',
    name: 'Classic',
    description: 'Deep navy and gold. Formal, traditional, distinguished.',
    primary_color: '#1a2744',
    accent_color: '#b8952a',
    headingFont: 'font-serif italic',
    bodyFont: 'font-sans',
    previewBg: '#1a2744',
    previewText: '#f0ead8',
    previewAccent: '#b8952a',
    card_radius: 2,
    hero_height: 'medium',
    grid_columns: 4,
    image_ratio: 'square',
    card_padding: 'normal',
    card_metadata: 'full',
    layout_variant: 'standard',
    supports_header_image: true,
  },
  {
    id: 'cover',
    name: 'Cover',
    description: 'Full-viewport hero image with your name overlaid. The collection reveals on scroll.',
    primary_color: '#1a1a1a',
    accent_color: '#e8d5b0',
    headingFont: 'font-serif italic',
    bodyFont: 'font-sans',
    previewBg: '#2a2318',
    previewText: '#f5f0e8',
    previewAccent: '#e8d5b0',
    card_radius: 6,
    hero_height: 'fullscreen',
    grid_columns: 3,
    image_ratio: 'portrait',
    card_padding: 'normal',
    card_metadata: 'title+artist',
    layout_variant: 'cover',
    supports_header_image: true,
  },
  {
    id: 'curator',
    name: 'Curator',
    description: 'Text-first. Opens with a large, elegant introduction, then the collection.',
    primary_color: '#2d2d2d',
    accent_color: '#7a6a52',
    headingFont: 'font-serif italic',
    bodyFont: 'font-sans',
    previewBg: '#faf8f5',
    previewText: '#2d2d2d',
    previewAccent: '#7a6a52',
    card_radius: 0,
    hero_height: 'none',
    grid_columns: 4,
    image_ratio: 'square',
    card_padding: 'tight',
    card_metadata: 'title+artist',
    layout_variant: 'text-forward',
    supports_header_image: false,
  },
  {
    id: 'magazine',
    name: 'Magazine',
    description: 'Featured works fill the top in a bold asymmetric layout. High impact.',
    primary_color: '#0d0d0d',
    accent_color: '#e63323',
    headingFont: 'font-serif',
    bodyFont: 'font-sans',
    previewBg: '#ffffff',
    previewText: '#0d0d0d',
    previewAccent: '#e63323',
    card_radius: 0,
    hero_height: 'none',
    grid_columns: 3,
    image_ratio: 'landscape',
    card_padding: 'tight',
    card_metadata: 'title+artist',
    layout_variant: 'magazine',
    supports_header_image: false,
  },
  {
    id: 'salon',
    name: 'Salon',
    description: 'Fixed sidebar with your identity; the collection fills the right panel.',
    primary_color: '#1c1917',
    accent_color: '#a3886a',
    headingFont: 'font-serif italic',
    bodyFont: 'font-sans',
    previewBg: '#fafaf9',
    previewText: '#1c1917',
    previewAccent: '#a3886a',
    card_radius: 4,
    hero_height: 'none',
    grid_columns: 3,
    image_ratio: 'square',
    card_padding: 'normal',
    card_metadata: 'title+artist',
    layout_variant: 'sidebar',
    supports_header_image: false,
  },
]

export function getTemplate(id: string): Template {
  return TEMPLATES.find(t => t.id === id) || TEMPLATES[0]
}